### ISSUE TITLE
Mount rotation gets forgotten

### ISSUE THREAD

**Issue by lpgagnon** [KSP-RO/ROTanks#68]
Build rocket, give it a rotatable mount, rotate the mount, all seems fine. Start a sim: mount is back to non-rotated state. Revert to vab: mount is still unrotated, and the rotation sliders have disappeared. Selecting a different mount then back to original brings the sliders back.

Same with saving & loading .craft files; after load, rotation is reset and sliders are missing, sliders come back after changing nose/core/mount selection

I'm guessing the "real bug" is the missing sliders, and the rotation reset is a consequence of that

ROLib 1.3.1, ROTanks 2.5

(originally mentioned on discord to see if anyone would confirm, but nobody bit)

**Comment by Falki-git** [comment]
Can confirm.

ROLib 1.3.1, ROTanks 2.5

Before SIM:
![before SIM](https://user-images.githubusercontent.com/72734856/141644788-1fefe433-6d83-44c3-b817-2d41a0d81921.png)

After SIM:
![after SIM](https://user-images.githubusercontent.com/72734856/141644798-5854bb2f-e3c8-444e-bb90-3ee4747ebe8f.png)

**Comment by al2me6** [comment]
Fixed by https://github.com/KSP-RO/ROLibrary/commit/4fbcd31259cd7ce9bfdf98a30773651ae7ddcbd2.

FWIW, there were three bugs:

* Rotations got reset on load
* Mounts' intrinsic rotation offsets were not dealt with coherently
* Rotations were getting double-applied when switching variants while there is a nonzero offset
